### ISSUE TITLE
Webservice und Peer to Peer Recherchieren

### ISSUE THREAD

**Issue by vietdung-truong** [vietdung-truong/hsnrverteilteanwendungenss2018#11]
und David schicken zum Implementieren.

**Comment by raphzahn1** [comment]
Das ist eine gute Integration von IPFS und einer Blockchain. Es lohnt sich, wenn man große Daten zu Transaktionen speichern möchte: https://medium.com/@mycoralhealth/learn-to-securely-share-files-on-the-blockchain-with-ipfs-219ee47df54c

**Comment by momo0596** [comment]
Tutorial zur Erstellung einer IPFS Application: 

https://www.youtube.com/watch?v=ADoRVVOSpI8

**Comment by momo0596** [comment]
Hilfreiche Repo bei der Verwendung von IPFS: 

https://github.com/ipfs/awesome-ipfs

**Comment by momo0596** [comment]
Multithread Ansatz: 


http://what-when-how.com/Tutorial/Multithreaded-Programming-with-JAVA/Multithreaded-Programming-with-JAVA-00179.html
