### ISSUE TITLE
Informative Links 

### ISSUE THREAD

**Issue by momo0596** [vietdung-truong/hsnrverteilteanwendungenss2018#13]
https://medium.com/@ssaurel/create-your-own-blockchain-in-30-minutes-dbde3293b390

**Comment by raphzahn1** [comment]
Ein gutes Tutorial zu einem Peer 2 Peer Chat:

https://www.youtube.com/watch?v=Q-wzRVgqM-M&list=PLg666f6d82X7eWghHq0vesWEZfIwHkpv4

**Comment by vietdung-truong** [comment]
habe beide gelesen und programmiert. Danke!
