### ISSUE TITLE
Fragen an Herrn Krings

### ISSUE THREAD

**Issue by vietdung-truong** [vietdung-truong/hsnrverteilteanwendungenss2018#18]
Sehr geehrter Herr Dr. Krings,  

könnten Sie uns bitte Auskunft geben, welche Art von Testszenarien für die Dokumentation gewünscht sind. 

Außerdem wollten wir Sie Fragen, ob der Abgabetermin der Dokumente der Präsentation Tag ist
oder am 06.07 2018 wie im Studierendenservice beschrieben .

Mit freundlichen Grüßen

**Comment by wysiib** [comment]
Hallo,
für die Szenarien reichen die wichtigen:
- Aufsetzen des Systems (von Null bis leere Wallets)
- Mining
- Kontenstandsabfrage / Einsicht ins Wallet
- Überweisungen.

Den Abgabetermin kläre ich wie gesagt noch.

MfG

Sebastian Krings

**Comment by wysiib** [comment]
Hallo,

Nachtrag: Bitte versuchen Sie, bis zur Abschlusspräsentation alles fertig zu haben. Sie können dann aber bis zum 6.7. noch Verbesserungen vornehmen, damit Sie auf eventuelle Anmerkungen / Kritik / Hinweise bei der Präsentation eingehen können.
