### ISSUE TITLE
Abgabe

### ISSUE THREAD

**Issue by raphzahn1** [vietdung-truong/hsnrverteilteanwendungenss2018#19]
Guten Tag Dr. Krings,

seid der Präsentation sind uns noch ein paar Fragen zu der Abgabe eingefallen. Aktuell befinden sich alle Mitglieder in der Klausurenphase, weshalb wir noch etwas Zeit für die Überarbeitung unserer Dokumentation brauchen. Können Sie uns bitte noch einmal mitteilen, In welcher Form Sie die Dokumente haben möchten (zum Beispiel als zip Ordner, oder als Hardcopy mit Abgabe in ihren Büro) . Sie hatten uns mitgeteilt, dass Sie alle Dokumente bis Mitte August haben möchten, also in diesem Fall den 15.August?. Bitte bestätigen Sie uns noch einmal den Termin.

Freundliche Grüße
Mohamed Tamer, Viet Dung Truong und Raphael Palombo

**Comment by wysiib** [comment]
Am liebsten wäre es mir, die Dokumente einfach mit in das Git Repository einzuchecken (z.B. in einen Ordner "docs"). So kann nichts weg kommen und wir haben alles beieinander. 15. August ist für mich in Ordnung.
