### ISSUE TITLE
Besprechungstunde mit Herrn Krings

### ISSUE THREAD

**Issue by vietdung-truong** [vietdung-truong/hsnrverteilteanwendungenss2018#2]
sehr geehrte Herr Krings,

wir haben leider Ihre Email Adresse nicht gefunden. Wir würden gerne einen Termin mit ihnen für nächste Woche am 24.04.2018 um 10 Uhr vereinbaren. Würde es Ihnen passen?

Wir freuen uns auf Ihre Antwort und verbleiben mit freundlichen Grüßen,
Viet-Dung Truong

**Comment by wysiib** [comment]
Termin passt!
