### ISSUE TITLE
GitHub Commit issue

### ISSUE THREAD

**Issue by vietdung-truong** [vietdung-truong/hsnrverteilteanwendungenss2018#6]
Ich bin morgen oder übermorgen in Tschechien und werde versuchen, mit einem zweitem PC an den Projekt weiter.

Versuch dieses Tutorial:
https://www.youtube.com/watch?v=riRuOSswRxA

**Comment by momo0596** [comment]
![image](https://user-images.githubusercontent.com/38244244/39672288-db84808a-5127-11e8-9bd4-0b9abe5cf928.png)


![image](https://user-images.githubusercontent.com/38244244/39672290-e20b841c-5127-11e8-9449-2167fcbd23af.png)

![image](https://user-images.githubusercontent.com/38244244/39672292-e7b928d8-5127-11e8-9dcc-a20c48458a7d.png)

![image](https://user-images.githubusercontent.com/38244244/39672298-ebc8a17e-5127-11e8-91ec-92c4616e21d5.png)


![image](https://user-images.githubusercontent.com/38244244/39672299-f0c9d422-5127-11e8-933e-c0d93dc1592c.png)

**Comment by momo0596** [comment]
Fehler der lokalen Entwicklungsumgebung wurde gefunden. Es handelte sich um ein Implementierungsfehler.
