### ISSUE TITLE
Präsentation Termin 

### ISSUE THREAD

**Issue by momo0596** [vietdung-truong/hsnrverteilteanwendungenss2018#7]
Hallo Herr Krings, 

in dem Skript auf moodle ist der Präsentationtermin auf den 10.05.18 . 

Dabei handelt es um ein Donnerstag. 
Handelt es sich dabei um ein Tippfehler da eigentlich der Dienstag in der Woche dazu vorgesehen ist. 

Mit freundlichen Grüßen

**Comment by wysiib** [comment]
Die Präsentation findet nächste Woche am 15.5. um 10 Uhr statt.
