### ISSUE TITLE
BouncyCastle Failure

### ISSUE THREAD

**Issue by momo0596** [vietdung-truong/hsnrverteilteanwendungenss2018#8]
Der aktuelle Quellecode wurde gefetched und die Bouncycastle Libary hinzugefügt. 

org.bouncyCastle kann nicht gefunden werden 

![unbenannt](https://user-images.githubusercontent.com/38244244/39703320-07299636-5208-11e8-86f4-23dab3ba1779.PNG)

**Comment by raphzahn1** [comment]
Es gab ein Problem mit Bouncy Castle. Mohamed und Raphael haben die Bibliothek selbst integriert und nicht die Bibliothek über Git Hub bezogen. So hat das Programm die Hauptklasse nicht erkannt
