### ISSUE TITLE
Links von Netbeans Tutorial schicken

### ISSUE THREAD

**Issue by vietdung-truong** [vietdung-truong/hsnrverteilteanwendungenss2018#9]

**Comment by momo0596** [comment]
https://bitcoinj.github.io/networking

**Comment by raphzahn1** [comment]
Hier ist der Link zu einem Netbeans Tutorial zur GUI Programmierung. Auf Lynda kommt Ihr über einen Link in der Digibib unter Datenbanken/ Volltexte Allgemeines  >> Lynda. Dort müsst Ihr euch Anmelden.

Link Digibib:

https://www.digibib.net/template/digilink/CategoryView?SID=MASTER:fa348c225f0c20f1e12ed61ea3a24ea6&LOCATION=829&FUNC=CategoryView&FILTER=All&CID=7726

Das tutorial:

https://www.lynda.com/Java-tutorials/Learn-Java-Swing/592496-2.html?srchtrk=index%3a1%0alinktypeid%3a2%0aq%3agui+swing+designer%0apage%3a1%0as%3arelevance%0asa%3atrue%0aproducttypeid%3a2
